
// Auto-Generated by generator.cc - Do not edit.
#include "gemm_rs/gemm_v2_reduce_scatter.hpp"
using namespace bytedance::flux;
using namespace cute;

using _GemmMetaT = decltype(make_gemm_meta(make_gemm_dtype_config(_FP16{},_FP16{},_FP16{},_FP16{},_FP32{},_FP32{}),_Sm80{},_A100{},_ReduceScatter{},_RRR{},_GemmV2{},make_gemm_v2_meta(_False{}),make_reduce_scatter_meta(_True{},_IntraNode{})));
struct _fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode : public _GemmMetaT {
  using _GemmMetaT::_GemmMetaT;
};
using GemmMetaT = _fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode;


using _GemmHParamsT_0 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_0 {
  using _GemmHParamsT_0::_GemmHParamsT_0;
};
using GemmHParamsT_0 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasterheuristic;
using KernelBuilder_0 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_0>;
using GemmKernel_0 = decltype(KernelBuilder_0().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasterheuristic: public GemmKernel_0 {};
using GemmDevice_0 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_0, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_1 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_1 {
  using _GemmHParamsT_1::_GemmHParamsT_1;
};
using GemmHParamsT_1 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic;
using KernelBuilder_1 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_1>;
using GemmKernel_1 = decltype(KernelBuilder_1().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic: public GemmKernel_1 {};
using GemmDevice_1 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_1, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_2 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_2 {
  using _GemmHParamsT_2::_GemmHParamsT_2;
};
using GemmHParamsT_2 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasterheuristic;
using KernelBuilder_2 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_2>;
using GemmKernel_2 = decltype(KernelBuilder_2().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasterheuristic: public GemmKernel_2 {};
using GemmDevice_2 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_2, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_3 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_3 {
  using _GemmHParamsT_3::_GemmHParamsT_3;
};
using GemmHParamsT_3 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasterheuristic;
using KernelBuilder_3 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_3>;
using GemmKernel_3 = decltype(KernelBuilder_3().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasterheuristic: public GemmKernel_3 {};
using GemmDevice_3 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_3, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_4 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_4 {
  using _GemmHParamsT_4::_GemmHParamsT_4;
};
using GemmHParamsT_4 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasterheuristic;
using KernelBuilder_4 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_4>;
using GemmKernel_4 = decltype(KernelBuilder_4().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasterheuristic: public GemmKernel_4 {};
using GemmDevice_4 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_4, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_5 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_5 {
  using _GemmHParamsT_5::_GemmHParamsT_5;
};
using GemmHParamsT_5 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasterheuristic;
using KernelBuilder_5 = GemmV2ReduceScatter_Kernel<GemmMetaT, GemmHParamsT_5>;
using GemmKernel_5 = decltype(KernelBuilder_5().gemm_kernel());
struct flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasterheuristic: public GemmKernel_5 {};
using GemmDevice_5 = GemmV2ReduceScatter_Device<GemmMetaT, GemmHParamsT_5, flux_fp16_fp16_fp16_fp16_fp32_fp32_sm80_a100_reducescatter_rrr_gemmv2_false_true_intranode_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasterheuristic>;

static bool _dummy_reg [[maybe_unused]] = (
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_0>(); }, GemmMetaT{},GemmHParamsT_0{},0),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_1>(); }, GemmMetaT{},GemmHParamsT_1{},1),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_2>(); }, GemmMetaT{},GemmHParamsT_2{},2),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_3>(); }, GemmMetaT{},GemmHParamsT_3{},3),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_4>(); }, GemmMetaT{},GemmHParamsT_4{},4),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_5>(); }, GemmMetaT{},GemmHParamsT_5{},5),
true);