# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /global/u1/y/yufeid/workspace/changchen/andrewy/flux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /global/homes/y/yufeid/workspace/changchen/andrewy/flux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /global/homes/y/yufeid/workspace/changchen/andrewy/flux/CMakeFiles /global/homes/y/yufeid/workspace/changchen/andrewy/flux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /global/homes/y/yufeid/workspace/changchen/andrewy/flux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FLUX_GENERATOR

# Build rule for target.
FLUX_GENERATOR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FLUX_GENERATOR
.PHONY : FLUX_GENERATOR

# fast build rule for target.
FLUX_GENERATOR/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/FLUX_GENERATOR.dir/build.make src/CMakeFiles/FLUX_GENERATOR.dir/build
.PHONY : FLUX_GENERATOR/fast

#=============================================================================
# Target rules for targets named flux_cuda_comm_none

# Build rule for target.
flux_cuda_comm_none: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_comm_none
.PHONY : flux_cuda_comm_none

# fast build rule for target.
flux_cuda_comm_none/fast:
	$(MAKE) $(MAKESILENT) -f src/comm_none/CMakeFiles/flux_cuda_comm_none.dir/build.make src/comm_none/CMakeFiles/flux_cuda_comm_none.dir/build
.PHONY : flux_cuda_comm_none/fast

#=============================================================================
# Target rules for targets named flux_coll

# Build rule for target.
flux_coll: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_coll
.PHONY : flux_coll

# fast build rule for target.
flux_coll/fast:
	$(MAKE) $(MAKESILENT) -f src/coll/CMakeFiles/flux_coll.dir/build.make src/coll/CMakeFiles/flux_coll.dir/build
.PHONY : flux_coll/fast

#=============================================================================
# Target rules for targets named flux_cuda_all_gather

# Build rule for target.
flux_cuda_all_gather: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_all_gather
.PHONY : flux_cuda_all_gather

# fast build rule for target.
flux_cuda_all_gather/fast:
	$(MAKE) $(MAKESILENT) -f src/ag_gemm/CMakeFiles/flux_cuda_all_gather.dir/build.make src/ag_gemm/CMakeFiles/flux_cuda_all_gather.dir/build
.PHONY : flux_cuda_all_gather/fast

#=============================================================================
# Target rules for targets named flux_cuda_reduce_scatter

# Build rule for target.
flux_cuda_reduce_scatter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_reduce_scatter
.PHONY : flux_cuda_reduce_scatter

# fast build rule for target.
flux_cuda_reduce_scatter/fast:
	$(MAKE) $(MAKESILENT) -f src/gemm_rs/CMakeFiles/flux_cuda_reduce_scatter.dir/build.make src/gemm_rs/CMakeFiles/flux_cuda_reduce_scatter.dir/build
.PHONY : flux_cuda_reduce_scatter/fast

#=============================================================================
# Target rules for targets named flux_cuda_gemm_a2a_transpose

# Build rule for target.
flux_cuda_gemm_a2a_transpose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_gemm_a2a_transpose
.PHONY : flux_cuda_gemm_a2a_transpose

# fast build rule for target.
flux_cuda_gemm_a2a_transpose/fast:
	$(MAKE) $(MAKESILENT) -f src/gemm_a2a_transpose/CMakeFiles/flux_cuda_gemm_a2a_transpose.dir/build.make src/gemm_a2a_transpose/CMakeFiles/flux_cuda_gemm_a2a_transpose.dir/build
.PHONY : flux_cuda_gemm_a2a_transpose/fast

#=============================================================================
# Target rules for targets named flux_cuda_all_to_all_gemm

# Build rule for target.
flux_cuda_all_to_all_gemm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_all_to_all_gemm
.PHONY : flux_cuda_all_to_all_gemm

# fast build rule for target.
flux_cuda_all_to_all_gemm/fast:
	$(MAKE) $(MAKESILENT) -f src/a2a_transpose_gemm/CMakeFiles/flux_cuda_all_to_all_gemm.dir/build.make src/a2a_transpose_gemm/CMakeFiles/flux_cuda_all_to_all_gemm.dir/build
.PHONY : flux_cuda_all_to_all_gemm/fast

#=============================================================================
# Target rules for targets named flux_cuda_inplace_cast

# Build rule for target.
flux_cuda_inplace_cast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_inplace_cast
.PHONY : flux_cuda_inplace_cast

# fast build rule for target.
flux_cuda_inplace_cast/fast:
	$(MAKE) $(MAKESILENT) -f src/inplace_cast/CMakeFiles/flux_cuda_inplace_cast.dir/build.make src/inplace_cast/CMakeFiles/flux_cuda_inplace_cast.dir/build
.PHONY : flux_cuda_inplace_cast/fast

#=============================================================================
# Target rules for targets named flux_cuda_quantization

# Build rule for target.
flux_cuda_quantization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_quantization
.PHONY : flux_cuda_quantization

# fast build rule for target.
flux_cuda_quantization/fast:
	$(MAKE) $(MAKESILENT) -f src/quantization/CMakeFiles/flux_cuda_quantization.dir/build.make src/quantization/CMakeFiles/flux_cuda_quantization.dir/build
.PHONY : flux_cuda_quantization/fast

#=============================================================================
# Target rules for targets named flux_cuda_moe_ag_scatter

# Build rule for target.
flux_cuda_moe_ag_scatter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_moe_ag_scatter
.PHONY : flux_cuda_moe_ag_scatter

# fast build rule for target.
flux_cuda_moe_ag_scatter/fast:
	$(MAKE) $(MAKESILENT) -f src/moe_ag_scatter/CMakeFiles/flux_cuda_moe_ag_scatter.dir/build.make src/moe_ag_scatter/CMakeFiles/flux_cuda_moe_ag_scatter.dir/build
.PHONY : flux_cuda_moe_ag_scatter/fast

#=============================================================================
# Target rules for targets named flux_cuda_moe_gather_rs

# Build rule for target.
flux_cuda_moe_gather_rs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_moe_gather_rs
.PHONY : flux_cuda_moe_gather_rs

# fast build rule for target.
flux_cuda_moe_gather_rs/fast:
	$(MAKE) $(MAKESILENT) -f src/moe_gather_rs/CMakeFiles/flux_cuda_moe_gather_rs.dir/build.make src/moe_gather_rs/CMakeFiles/flux_cuda_moe_gather_rs.dir/build
.PHONY : flux_cuda_moe_gather_rs/fast

#=============================================================================
# Target rules for targets named flux_cuda

# Build rule for target.
flux_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda
.PHONY : flux_cuda

# fast build rule for target.
flux_cuda/fast:
	$(MAKE) $(MAKESILENT) -f src/cuda/CMakeFiles/flux_cuda.dir/build.make src/cuda/CMakeFiles/flux_cuda.dir/build
.PHONY : flux_cuda/fast

#=============================================================================
# Target rules for targets named flux_cuda_ths_op

# Build rule for target.
flux_cuda_ths_op: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flux_cuda_ths_op
.PHONY : flux_cuda_ths_op

# fast build rule for target.
flux_cuda_ths_op/fast:
	$(MAKE) $(MAKESILENT) -f src/ths_op/CMakeFiles/flux_cuda_ths_op.dir/build.make src/ths_op/CMakeFiles/flux_cuda_ths_op.dir/build
.PHONY : flux_cuda_ths_op/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FLUX_GENERATOR"
	@echo "... flux_coll"
	@echo "... flux_cuda"
	@echo "... flux_cuda_all_gather"
	@echo "... flux_cuda_all_to_all_gemm"
	@echo "... flux_cuda_comm_none"
	@echo "... flux_cuda_gemm_a2a_transpose"
	@echo "... flux_cuda_inplace_cast"
	@echo "... flux_cuda_moe_ag_scatter"
	@echo "... flux_cuda_moe_gather_rs"
	@echo "... flux_cuda_quantization"
	@echo "... flux_cuda_reduce_scatter"
	@echo "... flux_cuda_ths_op"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

