
// Auto-Generated by generator.cc - Do not edit.
#include "moe_gather_rs/gemm_grouped_v2_gather_rs.hpp"
using namespace bytedance::flux;
using namespace cute;

using _GemmMetaT = decltype(make_gemm_meta(make_gemm_dtype_config(_BF16{},_BF16{},_BF16{},_BF16{},_FP32{},_FP32{}),_Sm80{},_A100{},_GatherRS{},_RCR{},_GemmGroupedV2{},make_gemm_v2_meta(_False{}),make_gather_rs_meta(cute::Int<1>{})));
struct _bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_gatherrs_rcr_gemmgroupedv2_false_1 : public _GemmMetaT {
  using _GemmMetaT::_GemmMetaT;
};
using GemmMetaT = _bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_gatherrs_rcr_gemmgroupedv2_false_1;


using _GemmHParamsT_0 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_0 {
  using _GemmHParamsT_0::_GemmHParamsT_0;
};
using GemmHParamsT_0 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic;
using KernelBuilder_0 = GemmGroupedV2GatherRS_Kernel<GemmMetaT, GemmHParamsT_0>;
using GemmKernel_0 = decltype(KernelBuilder_0().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_gatherrs_rcr_gemmgroupedv2_false_1_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic: public GemmKernel_0 {};
using GemmDevice_0 = GemmGroupedV2GatherRS_Device<GemmMetaT, GemmHParamsT_0, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_gatherrs_rcr_gemmgroupedv2_false_1_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasterheuristic>;

static bool _dummy_reg [[maybe_unused]] = (
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_0>(); }, GemmMetaT{},GemmHParamsT_0{},0),
true);