
// Auto-Generated by generator.cc - Do not edit.
#include "comm_none/gemm_v2_comm_none.hpp"
using namespace bytedance::flux;
using namespace cute;

using _GemmMetaT = decltype(make_gemm_meta(make_gemm_dtype_config(_S8{},_S8{},_Void{},_BF16{},_S32{},_FP32{}),_Sm80{},_A100{},_CommNone{},_RCR{},_GemmV2{},make_gemm_v2_meta(_False{}),None{}));
struct _s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil : public _GemmMetaT {
  using _GemmMetaT::_GemmMetaT;
};
using GemmMetaT = _s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil;


using _GemmHParamsT_0 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_0 {
  using _GemmHParamsT_0::_GemmHParamsT_0;
};
using GemmHParamsT_0 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_0 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_0>;
using GemmKernel_0 = decltype(KernelBuilder_0().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongm: public GemmKernel_0 {};
using GemmDevice_0 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_0, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_1 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_1 {
  using _GemmHParamsT_1::_GemmHParamsT_1;
};
using GemmHParamsT_1 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_1 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_1>;
using GemmKernel_1 = decltype(KernelBuilder_1().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongn: public GemmKernel_1 {};
using GemmDevice_1 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_1, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_2 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_2 {
  using _GemmHParamsT_2::_GemmHParamsT_2;
};
using GemmHParamsT_2 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_2 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_2>;
using GemmKernel_2 = decltype(KernelBuilder_2().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasterheuristic: public GemmKernel_2 {};
using GemmDevice_2 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_2, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_3 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_3 {
  using _GemmHParamsT_3::_GemmHParamsT_3;
};
using GemmHParamsT_3 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_3 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_3>;
using GemmKernel_3 = decltype(KernelBuilder_3().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongm: public GemmKernel_3 {};
using GemmDevice_3 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_3, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_4 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_4 {
  using _GemmHParamsT_4::_GemmHParamsT_4;
};
using GemmHParamsT_4 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_4 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_4>;
using GemmKernel_4 = decltype(KernelBuilder_4().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongn: public GemmKernel_4 {};
using GemmDevice_4 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_4, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_5 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_5 {
  using _GemmHParamsT_5::_GemmHParamsT_5;
};
using GemmHParamsT_5 = _64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_5 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_5>;
using GemmKernel_5 = decltype(KernelBuilder_5().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasterheuristic: public GemmKernel_5 {};
using GemmDevice_5 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_5, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x64x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_6 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_6 {
  using _GemmHParamsT_6::_GemmHParamsT_6;
};
using GemmHParamsT_6 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_6 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_6>;
using GemmKernel_6 = decltype(KernelBuilder_6().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongm: public GemmKernel_6 {};
using GemmDevice_6 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_6, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_7 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_7 {
  using _GemmHParamsT_7::_GemmHParamsT_7;
};
using GemmHParamsT_7 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_7 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_7>;
using GemmKernel_7 = decltype(KernelBuilder_7().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongn: public GemmKernel_7 {};
using GemmDevice_7 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_7, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_8 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_8 {
  using _GemmHParamsT_8::_GemmHParamsT_8;
};
using GemmHParamsT_8 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_8 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_8>;
using GemmKernel_8 = decltype(KernelBuilder_8().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasterheuristic: public GemmKernel_8 {};
using GemmDevice_8 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_8, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_9 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_9 {
  using _GemmHParamsT_9::_GemmHParamsT_9;
};
using GemmHParamsT_9 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_9 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_9>;
using GemmKernel_9 = decltype(KernelBuilder_9().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongm: public GemmKernel_9 {};
using GemmDevice_9 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_9, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_10 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_10 {
  using _GemmHParamsT_10::_GemmHParamsT_10;
};
using GemmHParamsT_10 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_10 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_10>;
using GemmKernel_10 = decltype(KernelBuilder_10().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongn: public GemmKernel_10 {};
using GemmDevice_10 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_10, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_11 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_11 {
  using _GemmHParamsT_11::_GemmHParamsT_11;
};
using GemmHParamsT_11 = _64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_11 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_11>;
using GemmKernel_11 = decltype(KernelBuilder_11().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasterheuristic: public GemmKernel_11 {};
using GemmDevice_11 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_11, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_128x128x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_12 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_12 {
  using _GemmHParamsT_12::_GemmHParamsT_12;
};
using GemmHParamsT_12 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_12 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_12>;
using GemmKernel_12 = decltype(KernelBuilder_12().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongm: public GemmKernel_12 {};
using GemmDevice_12 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_12, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_13 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_13 {
  using _GemmHParamsT_13::_GemmHParamsT_13;
};
using GemmHParamsT_13 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_13 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_13>;
using GemmKernel_13 = decltype(KernelBuilder_13().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongn: public GemmKernel_13 {};
using GemmDevice_13 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_13, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_14 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_14 {
  using _GemmHParamsT_14::_GemmHParamsT_14;
};
using GemmHParamsT_14 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_14 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_14>;
using GemmKernel_14 = decltype(KernelBuilder_14().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasterheuristic: public GemmKernel_14 {};
using GemmDevice_14 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_14, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_15 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_15 {
  using _GemmHParamsT_15::_GemmHParamsT_15;
};
using GemmHParamsT_15 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_15 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_15>;
using GemmKernel_15 = decltype(KernelBuilder_15().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongm: public GemmKernel_15 {};
using GemmDevice_15 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_15, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_16 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_16 {
  using _GemmHParamsT_16::_GemmHParamsT_16;
};
using GemmHParamsT_16 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_16 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_16>;
using GemmKernel_16 = decltype(KernelBuilder_16().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongn: public GemmKernel_16 {};
using GemmDevice_16 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_16, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_17 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_17 {
  using _GemmHParamsT_17::_GemmHParamsT_17;
};
using GemmHParamsT_17 = _64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_17 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_17>;
using GemmKernel_17 = decltype(KernelBuilder_17().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasterheuristic: public GemmKernel_17 {};
using GemmDevice_17 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_17, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamksk_nil_64x64x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_18 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_18 {
  using _GemmHParamsT_18::_GemmHParamsT_18;
};
using GemmHParamsT_18 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_18 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_18>;
using GemmKernel_18 = decltype(KernelBuilder_18().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongm: public GemmKernel_18 {};
using GemmDevice_18 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_18, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_19 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_19 {
  using _GemmHParamsT_19::_GemmHParamsT_19;
};
using GemmHParamsT_19 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_19 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_19>;
using GemmKernel_19 = decltype(KernelBuilder_19().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongn: public GemmKernel_19 {};
using GemmDevice_19 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_19, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_20 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_20 {
  using _GemmHParamsT_20::_GemmHParamsT_20;
};
using GemmHParamsT_20 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_20 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_20>;
using GemmKernel_20 = decltype(KernelBuilder_20().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasterheuristic: public GemmKernel_20 {};
using GemmDevice_20 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_20, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_21 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_21 {
  using _GemmHParamsT_21::_GemmHParamsT_21;
};
using GemmHParamsT_21 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_21 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_21>;
using GemmKernel_21 = decltype(KernelBuilder_21().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongm: public GemmKernel_21 {};
using GemmDevice_21 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_21, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_22 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_22 {
  using _GemmHParamsT_22::_GemmHParamsT_22;
};
using GemmHParamsT_22 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_22 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_22>;
using GemmKernel_22 = decltype(KernelBuilder_22().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongn: public GemmKernel_22 {};
using GemmDevice_22 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_22, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_23 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_23 {
  using _GemmHParamsT_23::_GemmHParamsT_23;
};
using GemmHParamsT_23 = _64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_23 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_23>;
using GemmKernel_23 = decltype(KernelBuilder_23().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasterheuristic: public GemmKernel_23 {};
using GemmDevice_23 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_23, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x64x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_24 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_24 {
  using _GemmHParamsT_24::_GemmHParamsT_24;
};
using GemmHParamsT_24 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_24 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_24>;
using GemmKernel_24 = decltype(KernelBuilder_24().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongm: public GemmKernel_24 {};
using GemmDevice_24 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_24, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_25 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_25 {
  using _GemmHParamsT_25::_GemmHParamsT_25;
};
using GemmHParamsT_25 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_25 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_25>;
using GemmKernel_25 = decltype(KernelBuilder_25().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongn: public GemmKernel_25 {};
using GemmDevice_25 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_25, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_26 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_26 {
  using _GemmHParamsT_26::_GemmHParamsT_26;
};
using GemmHParamsT_26 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_26 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_26>;
using GemmKernel_26 = decltype(KernelBuilder_26().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasterheuristic: public GemmKernel_26 {};
using GemmDevice_26 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_26, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_27 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_27 {
  using _GemmHParamsT_27::_GemmHParamsT_27;
};
using GemmHParamsT_27 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_27 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_27>;
using GemmKernel_27 = decltype(KernelBuilder_27().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongm: public GemmKernel_27 {};
using GemmDevice_27 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_27, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_28 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_28 {
  using _GemmHParamsT_28::_GemmHParamsT_28;
};
using GemmHParamsT_28 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_28 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_28>;
using GemmKernel_28 = decltype(KernelBuilder_28().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongn: public GemmKernel_28 {};
using GemmDevice_28 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_28, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_29 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_29 {
  using _GemmHParamsT_29::_GemmHParamsT_29;
};
using GemmHParamsT_29 = _64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_29 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_29>;
using GemmKernel_29 = decltype(KernelBuilder_29().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasterheuristic: public GemmKernel_29 {};
using GemmDevice_29 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_29, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_128x128x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_30 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongm : public _GemmHParamsT_30 {
  using _GemmHParamsT_30::_GemmHParamsT_30;
};
using GemmHParamsT_30 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongm;
using KernelBuilder_30 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_30>;
using GemmKernel_30 = decltype(KernelBuilder_30().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongm: public GemmKernel_30 {};
using GemmDevice_30 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_30, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_31 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongn : public _GemmHParamsT_31 {
  using _GemmHParamsT_31::_GemmHParamsT_31;
};
using GemmHParamsT_31 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongn;
using KernelBuilder_31 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_31>;
using GemmKernel_31 = decltype(KernelBuilder_31().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongn: public GemmKernel_31 {};
using GemmDevice_31 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_31, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_32 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<3>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasterheuristic : public _GemmHParamsT_32 {
  using _GemmHParamsT_32::_GemmHParamsT_32;
};
using GemmHParamsT_32 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasterheuristic;
using KernelBuilder_32 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_32>;
using GemmKernel_32 = decltype(KernelBuilder_32().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasterheuristic: public GemmKernel_32 {};
using GemmDevice_32 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_32, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_3_rasterheuristic>;


using _GemmHParamsT_33 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongm : public _GemmHParamsT_33 {
  using _GemmHParamsT_33::_GemmHParamsT_33;
};
using GemmHParamsT_33 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongm;
using KernelBuilder_33 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_33>;
using GemmKernel_33 = decltype(KernelBuilder_33().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongm: public GemmKernel_33 {};
using GemmDevice_33 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_33, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_34 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongn : public _GemmHParamsT_34 {
  using _GemmHParamsT_34::_GemmHParamsT_34;
};
using GemmHParamsT_34 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongn;
using KernelBuilder_34 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_34>;
using GemmKernel_34 = decltype(KernelBuilder_34().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongn: public GemmKernel_34 {};
using GemmDevice_34 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_34, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_35 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<32>{},cute::Int<128>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<128>{}),_GemmStreamK{},cute::Int<4>{},_RasterHeuristic{}));
struct _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasterheuristic : public _GemmHParamsT_35 {
  using _GemmHParamsT_35::_GemmHParamsT_35;
};
using GemmHParamsT_35 = _64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasterheuristic;
using KernelBuilder_35 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_35>;
using GemmKernel_35 = decltype(KernelBuilder_35().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasterheuristic: public GemmKernel_35 {};
using GemmDevice_35 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_35, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x32x128_16x8x32_streamkdp_nil_64x64x128_gemmstreamk_4_rasterheuristic>;


using _GemmHParamsT_36 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterAlongM{}));
struct _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongm : public _GemmHParamsT_36 {
  using _GemmHParamsT_36::_GemmHParamsT_36;
};
using GemmHParamsT_36 = _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongm;
using KernelBuilder_36 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_36>;
using GemmKernel_36 = decltype(KernelBuilder_36().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongm: public GemmKernel_36 {};
using GemmDevice_36 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_36, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongm>;


using _GemmHParamsT_37 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterAlongN{}));
struct _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongn : public _GemmHParamsT_37 {
  using _GemmHParamsT_37::_GemmHParamsT_37;
};
using GemmHParamsT_37 = _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongn;
using KernelBuilder_37 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_37>;
using GemmKernel_37 = decltype(KernelBuilder_37().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongn: public GemmKernel_37 {};
using GemmDevice_37 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_37, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasteralongn>;


using _GemmHParamsT_38 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterHeuristic{}));
struct _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasterheuristic : public _GemmHParamsT_38 {
  using _GemmHParamsT_38::_GemmHParamsT_38;
};
using GemmHParamsT_38 = _64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasterheuristic;
using KernelBuilder_38 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_38>;
using GemmKernel_38 = decltype(KernelBuilder_38().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasterheuristic: public GemmKernel_38 {};
using GemmDevice_38 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_38, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamksk_nil_128x128x64_gemmstreamk_5_rasterheuristic>;


using _GemmHParamsT_39 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterAlongM{}));
struct _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongm : public _GemmHParamsT_39 {
  using _GemmHParamsT_39::_GemmHParamsT_39;
};
using GemmHParamsT_39 = _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongm;
using KernelBuilder_39 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_39>;
using GemmKernel_39 = decltype(KernelBuilder_39().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongm: public GemmKernel_39 {};
using GemmDevice_39 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_39, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongm>;


using _GemmHParamsT_40 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterAlongN{}));
struct _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongn : public _GemmHParamsT_40 {
  using _GemmHParamsT_40::_GemmHParamsT_40;
};
using GemmHParamsT_40 = _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongn;
using KernelBuilder_40 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_40>;
using GemmKernel_40 = decltype(KernelBuilder_40().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongn: public GemmKernel_40 {};
using GemmDevice_40 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_40, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasteralongn>;


using _GemmHParamsT_41 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<64>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<32>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<5>{},_RasterHeuristic{}));
struct _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasterheuristic : public _GemmHParamsT_41 {
  using _GemmHParamsT_41::_GemmHParamsT_41;
};
using GemmHParamsT_41 = _64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasterheuristic;
using KernelBuilder_41 = GemmV2CommNone_Kernel<GemmMetaT, GemmHParamsT_41>;
using GemmKernel_41 = decltype(KernelBuilder_41().gemm_kernel());
struct flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasterheuristic: public GemmKernel_41 {};
using GemmDevice_41 = GemmV2CommNone_Device<GemmMetaT, GemmHParamsT_41, flux_s8_s8_void_bf16_s32_fp32_sm80_a100_commnone_rcr_gemmv2_false_nil_64x64x64_16x8x32_streamkdp_nil_128x128x64_gemmstreamk_5_rasterheuristic>;

static bool _dummy_reg [[maybe_unused]] = (
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_0>(); }, GemmMetaT{},GemmHParamsT_0{},0),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_1>(); }, GemmMetaT{},GemmHParamsT_1{},1),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_2>(); }, GemmMetaT{},GemmHParamsT_2{},2),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_3>(); }, GemmMetaT{},GemmHParamsT_3{},3),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_4>(); }, GemmMetaT{},GemmHParamsT_4{},4),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_5>(); }, GemmMetaT{},GemmHParamsT_5{},5),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_6>(); }, GemmMetaT{},GemmHParamsT_6{},6),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_7>(); }, GemmMetaT{},GemmHParamsT_7{},7),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_8>(); }, GemmMetaT{},GemmHParamsT_8{},8),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_9>(); }, GemmMetaT{},GemmHParamsT_9{},9),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_10>(); }, GemmMetaT{},GemmHParamsT_10{},10),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_11>(); }, GemmMetaT{},GemmHParamsT_11{},11),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_12>(); }, GemmMetaT{},GemmHParamsT_12{},12),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_13>(); }, GemmMetaT{},GemmHParamsT_13{},13),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_14>(); }, GemmMetaT{},GemmHParamsT_14{},14),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_15>(); }, GemmMetaT{},GemmHParamsT_15{},15),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_16>(); }, GemmMetaT{},GemmHParamsT_16{},16),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_17>(); }, GemmMetaT{},GemmHParamsT_17{},17),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_18>(); }, GemmMetaT{},GemmHParamsT_18{},18),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_19>(); }, GemmMetaT{},GemmHParamsT_19{},19),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_20>(); }, GemmMetaT{},GemmHParamsT_20{},20),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_21>(); }, GemmMetaT{},GemmHParamsT_21{},21),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_22>(); }, GemmMetaT{},GemmHParamsT_22{},22),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_23>(); }, GemmMetaT{},GemmHParamsT_23{},23),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_24>(); }, GemmMetaT{},GemmHParamsT_24{},24),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_25>(); }, GemmMetaT{},GemmHParamsT_25{},25),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_26>(); }, GemmMetaT{},GemmHParamsT_26{},26),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_27>(); }, GemmMetaT{},GemmHParamsT_27{},27),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_28>(); }, GemmMetaT{},GemmHParamsT_28{},28),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_29>(); }, GemmMetaT{},GemmHParamsT_29{},29),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_30>(); }, GemmMetaT{},GemmHParamsT_30{},30),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_31>(); }, GemmMetaT{},GemmHParamsT_31{},31),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_32>(); }, GemmMetaT{},GemmHParamsT_32{},32),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_33>(); }, GemmMetaT{},GemmHParamsT_33{},33),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_34>(); }, GemmMetaT{},GemmHParamsT_34{},34),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_35>(); }, GemmMetaT{},GemmHParamsT_35{},35),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_36>(); }, GemmMetaT{},GemmHParamsT_36{},36),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_37>(); }, GemmMetaT{},GemmHParamsT_37{},37),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_38>(); }, GemmMetaT{},GemmHParamsT_38{},38),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_39>(); }, GemmMetaT{},GemmHParamsT_39{},39),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_40>(); }, GemmMetaT{},GemmHParamsT_40{},40),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_41>(); }, GemmMetaT{},GemmHParamsT_41{},41),
true);