
// Auto-Generated by generator.cc - Do not edit.
#include "ag_gemm/gemm_v2_ag_kernel.hpp"
using namespace bytedance::flux;
using namespace cute;

using _GemmMetaT = decltype(make_gemm_meta(make_gemm_dtype_config(_BF16{},_BF16{},_BF16{},_BF16{},_FP32{},_FP32{}),_Sm80{},_A100{},_AGKernel{},_RRR{},_GemmV2{},make_gemm_v2_meta(_False{}),None{}));
struct _bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil : public _GemmMetaT {
  using _GemmMetaT::_GemmMetaT;
};
using GemmMetaT = _bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil;


using _GemmHParamsT_0 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_0 {
  using _GemmHParamsT_0::_GemmHParamsT_0;
};
using GemmHParamsT_0 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_0 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_0>;
using GemmKernel_0 = decltype(KernelBuilder_0().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongm: public GemmKernel_0 {};
using GemmDevice_0 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_0, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_1 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_1 {
  using _GemmHParamsT_1::_GemmHParamsT_1;
};
using GemmHParamsT_1 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_1 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_1>;
using GemmKernel_1 = decltype(KernelBuilder_1().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongn: public GemmKernel_1 {};
using GemmDevice_1 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_1, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_2 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_2 {
  using _GemmHParamsT_2::_GemmHParamsT_2;
};
using GemmHParamsT_2 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_2 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_2>;
using GemmKernel_2 = decltype(KernelBuilder_2().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongm: public GemmKernel_2 {};
using GemmDevice_2 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_2, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_3 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_3 {
  using _GemmHParamsT_3::_GemmHParamsT_3;
};
using GemmHParamsT_3 = _64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_3 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_3>;
using GemmKernel_3 = decltype(KernelBuilder_3().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongn: public GemmKernel_3 {};
using GemmDevice_3 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_3, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_4 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_4 {
  using _GemmHParamsT_4::_GemmHParamsT_4;
};
using GemmHParamsT_4 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_4 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_4>;
using GemmKernel_4 = decltype(KernelBuilder_4().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_4 {};
using GemmDevice_4 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_4, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_5 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_5 {
  using _GemmHParamsT_5::_GemmHParamsT_5;
};
using GemmHParamsT_5 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_5 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_5>;
using GemmKernel_5 = decltype(KernelBuilder_5().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_5 {};
using GemmDevice_5 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_5, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_6 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_6 {
  using _GemmHParamsT_6::_GemmHParamsT_6;
};
using GemmHParamsT_6 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_6 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_6>;
using GemmKernel_6 = decltype(KernelBuilder_6().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_6 {};
using GemmDevice_6 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_6, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_7 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_7 {
  using _GemmHParamsT_7::_GemmHParamsT_7;
};
using GemmHParamsT_7 = _64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_7 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_7>;
using GemmKernel_7 = decltype(KernelBuilder_7().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_7 {};
using GemmDevice_7 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_7, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x128x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_8 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_8 {
  using _GemmHParamsT_8::_GemmHParamsT_8;
};
using GemmHParamsT_8 = _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_8 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_8>;
using GemmKernel_8 = decltype(KernelBuilder_8().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_8 {};
using GemmDevice_8 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_8, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_9 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_9 {
  using _GemmHParamsT_9::_GemmHParamsT_9;
};
using GemmHParamsT_9 = _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_9 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_9>;
using GemmKernel_9 = decltype(KernelBuilder_9().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_9 {};
using GemmDevice_9 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_9, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_10 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_10 {
  using _GemmHParamsT_10::_GemmHParamsT_10;
};
using GemmHParamsT_10 = _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_10 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_10>;
using GemmKernel_10 = decltype(KernelBuilder_10().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_10 {};
using GemmDevice_10 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_10, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_11 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_11 {
  using _GemmHParamsT_11::_GemmHParamsT_11;
};
using GemmHParamsT_11 = _64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_11 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_11>;
using GemmKernel_11 = decltype(KernelBuilder_11().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_11 {};
using GemmDevice_11 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_11, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_12 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_12 {
  using _GemmHParamsT_12::_GemmHParamsT_12;
};
using GemmHParamsT_12 = _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_12 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_12>;
using GemmKernel_12 = decltype(KernelBuilder_12().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongm: public GemmKernel_12 {};
using GemmDevice_12 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_12, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_13 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_13 {
  using _GemmHParamsT_13::_GemmHParamsT_13;
};
using GemmHParamsT_13 = _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_13 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_13>;
using GemmKernel_13 = decltype(KernelBuilder_13().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongn: public GemmKernel_13 {};
using GemmDevice_13 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_13, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_14 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_14 {
  using _GemmHParamsT_14::_GemmHParamsT_14;
};
using GemmHParamsT_14 = _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_14 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_14>;
using GemmKernel_14 = decltype(KernelBuilder_14().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongm: public GemmKernel_14 {};
using GemmDevice_14 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_14, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_15 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_15 {
  using _GemmHParamsT_15::_GemmHParamsT_15;
};
using GemmHParamsT_15 = _64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_15 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_15>;
using GemmKernel_15 = decltype(KernelBuilder_15().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongn: public GemmKernel_15 {};
using GemmDevice_15 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_15, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x128x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_16 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_16 {
  using _GemmHParamsT_16::_GemmHParamsT_16;
};
using GemmHParamsT_16 = _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_16 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_16>;
using GemmKernel_16 = decltype(KernelBuilder_16().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongm: public GemmKernel_16 {};
using GemmDevice_16 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_16, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_17 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_17 {
  using _GemmHParamsT_17::_GemmHParamsT_17;
};
using GemmHParamsT_17 = _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_17 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_17>;
using GemmKernel_17 = decltype(KernelBuilder_17().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongn: public GemmKernel_17 {};
using GemmDevice_17 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_17, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_18 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_18 {
  using _GemmHParamsT_18::_GemmHParamsT_18;
};
using GemmHParamsT_18 = _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_18 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_18>;
using GemmKernel_18 = decltype(KernelBuilder_18().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongm: public GemmKernel_18 {};
using GemmDevice_18 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_18, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_19 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_19 {
  using _GemmHParamsT_19::_GemmHParamsT_19;
};
using GemmHParamsT_19 = _64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_19 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_19>;
using GemmKernel_19 = decltype(KernelBuilder_19().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongn: public GemmKernel_19 {};
using GemmDevice_19 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_19, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_20 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_20 {
  using _GemmHParamsT_20::_GemmHParamsT_20;
};
using GemmHParamsT_20 = _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_20 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_20>;
using GemmKernel_20 = decltype(KernelBuilder_20().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongm: public GemmKernel_20 {};
using GemmDevice_20 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_20, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_21 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_21 {
  using _GemmHParamsT_21::_GemmHParamsT_21;
};
using GemmHParamsT_21 = _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_21 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_21>;
using GemmKernel_21 = decltype(KernelBuilder_21().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongn: public GemmKernel_21 {};
using GemmDevice_21 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_21, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_22 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_22 {
  using _GemmHParamsT_22::_GemmHParamsT_22;
};
using GemmHParamsT_22 = _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_22 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_22>;
using GemmKernel_22 = decltype(KernelBuilder_22().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongm: public GemmKernel_22 {};
using GemmDevice_22 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_22, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_23 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_23 {
  using _GemmHParamsT_23::_GemmHParamsT_23;
};
using GemmHParamsT_23 = _64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_23 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_23>;
using GemmKernel_23 = decltype(KernelBuilder_23().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongn: public GemmKernel_23 {};
using GemmDevice_23 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_23, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_64x256x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_24 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_24 {
  using _GemmHParamsT_24::_GemmHParamsT_24;
};
using GemmHParamsT_24 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_24 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_24>;
using GemmKernel_24 = decltype(KernelBuilder_24().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongm: public GemmKernel_24 {};
using GemmDevice_24 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_24, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_25 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_25 {
  using _GemmHParamsT_25::_GemmHParamsT_25;
};
using GemmHParamsT_25 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_25 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_25>;
using GemmKernel_25 = decltype(KernelBuilder_25().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongn: public GemmKernel_25 {};
using GemmDevice_25 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_25, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_26 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_26 {
  using _GemmHParamsT_26::_GemmHParamsT_26;
};
using GemmHParamsT_26 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_26 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_26>;
using GemmKernel_26 = decltype(KernelBuilder_26().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongm: public GemmKernel_26 {};
using GemmDevice_26 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_26, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_27 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_27 {
  using _GemmHParamsT_27::_GemmHParamsT_27;
};
using GemmHParamsT_27 = _64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_27 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_27>;
using GemmKernel_27 = decltype(KernelBuilder_27().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongn: public GemmKernel_27 {};
using GemmDevice_27 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_27, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_128x256x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_28 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_28 {
  using _GemmHParamsT_28::_GemmHParamsT_28;
};
using GemmHParamsT_28 = _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_28 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_28>;
using GemmKernel_28 = decltype(KernelBuilder_28().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_28 {};
using GemmDevice_28 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_28, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_29 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_29 {
  using _GemmHParamsT_29::_GemmHParamsT_29;
};
using GemmHParamsT_29 = _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_29 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_29>;
using GemmKernel_29 = decltype(KernelBuilder_29().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_29 {};
using GemmDevice_29 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_29, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_30 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_30 {
  using _GemmHParamsT_30::_GemmHParamsT_30;
};
using GemmHParamsT_30 = _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_30 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_30>;
using GemmKernel_30 = decltype(KernelBuilder_30().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_30 {};
using GemmDevice_30 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_30, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_31 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkSK{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_31 {
  using _GemmHParamsT_31::_GemmHParamsT_31;
};
using GemmHParamsT_31 = _64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_31 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_31>;
using GemmKernel_31 = decltype(KernelBuilder_31().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_31 {};
using GemmDevice_31 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_31, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamksk_nil_256x128x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_32 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_32 {
  using _GemmHParamsT_32::_GemmHParamsT_32;
};
using GemmHParamsT_32 = _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_32 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_32>;
using GemmKernel_32 = decltype(KernelBuilder_32().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongm: public GemmKernel_32 {};
using GemmDevice_32 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_32, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_33 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_33 {
  using _GemmHParamsT_33::_GemmHParamsT_33;
};
using GemmHParamsT_33 = _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_33 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_33>;
using GemmKernel_33 = decltype(KernelBuilder_33().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongn: public GemmKernel_33 {};
using GemmDevice_33 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_33, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_34 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_34 {
  using _GemmHParamsT_34::_GemmHParamsT_34;
};
using GemmHParamsT_34 = _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_34 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_34>;
using GemmKernel_34 = decltype(KernelBuilder_34().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongm: public GemmKernel_34 {};
using GemmDevice_34 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_34, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_35 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_35 {
  using _GemmHParamsT_35::_GemmHParamsT_35;
};
using GemmHParamsT_35 = _64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_35 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_35>;
using GemmKernel_35 = decltype(KernelBuilder_35().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongn: public GemmKernel_35 {};
using GemmDevice_35 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_35, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_36 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_36 {
  using _GemmHParamsT_36::_GemmHParamsT_36;
};
using GemmHParamsT_36 = _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_36 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_36>;
using GemmKernel_36 = decltype(KernelBuilder_36().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_36 {};
using GemmDevice_36 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_36, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_37 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_37 {
  using _GemmHParamsT_37::_GemmHParamsT_37;
};
using GemmHParamsT_37 = _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_37 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_37>;
using GemmKernel_37 = decltype(KernelBuilder_37().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_37 {};
using GemmDevice_37 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_37, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_38 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_38 {
  using _GemmHParamsT_38::_GemmHParamsT_38;
};
using GemmHParamsT_38 = _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_38 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_38>;
using GemmKernel_38 = decltype(KernelBuilder_38().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_38 {};
using GemmDevice_38 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_38, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_39 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_39 {
  using _GemmHParamsT_39::_GemmHParamsT_39;
};
using GemmHParamsT_39 = _64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_39 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_39>;
using GemmKernel_39 = decltype(KernelBuilder_39().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_39 {};
using GemmDevice_39 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_39, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x128x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_40 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_40 {
  using _GemmHParamsT_40::_GemmHParamsT_40;
};
using GemmHParamsT_40 = _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_40 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_40>;
using GemmKernel_40 = decltype(KernelBuilder_40().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_40 {};
using GemmDevice_40 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_40, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_41 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_41 {
  using _GemmHParamsT_41::_GemmHParamsT_41;
};
using GemmHParamsT_41 = _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_41 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_41>;
using GemmKernel_41 = decltype(KernelBuilder_41().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_41 {};
using GemmDevice_41 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_41, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_42 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_42 {
  using _GemmHParamsT_42::_GemmHParamsT_42;
};
using GemmHParamsT_42 = _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_42 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_42>;
using GemmKernel_42 = decltype(KernelBuilder_42().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_42 {};
using GemmDevice_42 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_42, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_43 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_43 {
  using _GemmHParamsT_43::_GemmHParamsT_43;
};
using GemmHParamsT_43 = _64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_43 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_43>;
using GemmKernel_43 = decltype(KernelBuilder_43().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_43 {};
using GemmDevice_43 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_43, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_44 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_44 {
  using _GemmHParamsT_44::_GemmHParamsT_44;
};
using GemmHParamsT_44 = _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_44 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_44>;
using GemmKernel_44 = decltype(KernelBuilder_44().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongm: public GemmKernel_44 {};
using GemmDevice_44 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_44, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_45 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_45 {
  using _GemmHParamsT_45::_GemmHParamsT_45;
};
using GemmHParamsT_45 = _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_45 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_45>;
using GemmKernel_45 = decltype(KernelBuilder_45().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongn: public GemmKernel_45 {};
using GemmDevice_45 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_45, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_46 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_46 {
  using _GemmHParamsT_46::_GemmHParamsT_46;
};
using GemmHParamsT_46 = _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_46 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_46>;
using GemmKernel_46 = decltype(KernelBuilder_46().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongm: public GemmKernel_46 {};
using GemmDevice_46 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_46, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_47 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<128>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_47 {
  using _GemmHParamsT_47::_GemmHParamsT_47;
};
using GemmHParamsT_47 = _64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_47 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_47>;
using GemmKernel_47 = decltype(KernelBuilder_47().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongn: public GemmKernel_47 {};
using GemmDevice_47 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_47, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x128x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_48 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_48 {
  using _GemmHParamsT_48::_GemmHParamsT_48;
};
using GemmHParamsT_48 = _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_48 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_48>;
using GemmKernel_48 = decltype(KernelBuilder_48().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongm: public GemmKernel_48 {};
using GemmDevice_48 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_48, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_49 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_49 {
  using _GemmHParamsT_49::_GemmHParamsT_49;
};
using GemmHParamsT_49 = _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_49 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_49>;
using GemmKernel_49 = decltype(KernelBuilder_49().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongn: public GemmKernel_49 {};
using GemmDevice_49 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_49, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_50 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_50 {
  using _GemmHParamsT_50::_GemmHParamsT_50;
};
using GemmHParamsT_50 = _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_50 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_50>;
using GemmKernel_50 = decltype(KernelBuilder_50().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongm: public GemmKernel_50 {};
using GemmDevice_50 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_50, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_51 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_51 {
  using _GemmHParamsT_51::_GemmHParamsT_51;
};
using GemmHParamsT_51 = _64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_51 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_51>;
using GemmKernel_51 = decltype(KernelBuilder_51().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongn: public GemmKernel_51 {};
using GemmDevice_51 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_51, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_52 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongm : public _GemmHParamsT_52 {
  using _GemmHParamsT_52::_GemmHParamsT_52;
};
using GemmHParamsT_52 = _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongm;
using KernelBuilder_52 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_52>;
using GemmKernel_52 = decltype(KernelBuilder_52().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongm: public GemmKernel_52 {};
using GemmDevice_52 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_52, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_53 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongn : public _GemmHParamsT_53 {
  using _GemmHParamsT_53::_GemmHParamsT_53;
};
using GemmHParamsT_53 = _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongn;
using KernelBuilder_53 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_53>;
using GemmKernel_53 = decltype(KernelBuilder_53().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongn: public GemmKernel_53 {};
using GemmDevice_53 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_53, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_54 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongm : public _GemmHParamsT_54 {
  using _GemmHParamsT_54::_GemmHParamsT_54;
};
using GemmHParamsT_54 = _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongm;
using KernelBuilder_54 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_54>;
using GemmKernel_54 = decltype(KernelBuilder_54().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongm: public GemmKernel_54 {};
using GemmDevice_54 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_54, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_55 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<64>{},cute::Int<256>{},cute::Int<64>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongn : public _GemmHParamsT_55 {
  using _GemmHParamsT_55::_GemmHParamsT_55;
};
using GemmHParamsT_55 = _64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongn;
using KernelBuilder_55 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_55>;
using GemmKernel_55 = decltype(KernelBuilder_55().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongn: public GemmKernel_55 {};
using GemmDevice_55 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_55, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_64x256x64_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_56 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_56 {
  using _GemmHParamsT_56::_GemmHParamsT_56;
};
using GemmHParamsT_56 = _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_56 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_56>;
using GemmKernel_56 = decltype(KernelBuilder_56().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongm: public GemmKernel_56 {};
using GemmDevice_56 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_56, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_57 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_57 {
  using _GemmHParamsT_57::_GemmHParamsT_57;
};
using GemmHParamsT_57 = _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_57 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_57>;
using GemmKernel_57 = decltype(KernelBuilder_57().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongn: public GemmKernel_57 {};
using GemmDevice_57 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_57, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_58 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_58 {
  using _GemmHParamsT_58::_GemmHParamsT_58;
};
using GemmHParamsT_58 = _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_58 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_58>;
using GemmKernel_58 = decltype(KernelBuilder_58().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongm: public GemmKernel_58 {};
using GemmDevice_58 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_58, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_59 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<128>{},cute::Int<256>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_59 {
  using _GemmHParamsT_59::_GemmHParamsT_59;
};
using GemmHParamsT_59 = _64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_59 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_59>;
using GemmKernel_59 = decltype(KernelBuilder_59().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongn: public GemmKernel_59 {};
using GemmDevice_59 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_59, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_128x256x32_gemmstreamk_4_rasteralongn>;


using _GemmHParamsT_60 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongm : public _GemmHParamsT_60 {
  using _GemmHParamsT_60::_GemmHParamsT_60;
};
using GemmHParamsT_60 = _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongm;
using KernelBuilder_60 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_60>;
using GemmKernel_60 = decltype(KernelBuilder_60().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongm: public GemmKernel_60 {};
using GemmDevice_60 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_60, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongm>;


using _GemmHParamsT_61 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<3>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongn : public _GemmHParamsT_61 {
  using _GemmHParamsT_61::_GemmHParamsT_61;
};
using GemmHParamsT_61 = _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongn;
using KernelBuilder_61 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_61>;
using GemmKernel_61 = decltype(KernelBuilder_61().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongn: public GemmKernel_61 {};
using GemmDevice_61 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_61, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_3_rasteralongn>;


using _GemmHParamsT_62 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongM{}));
struct _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongm : public _GemmHParamsT_62 {
  using _GemmHParamsT_62::_GemmHParamsT_62;
};
using GemmHParamsT_62 = _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongm;
using KernelBuilder_62 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_62>;
using GemmKernel_62 = decltype(KernelBuilder_62().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongm: public GemmKernel_62 {};
using GemmDevice_62 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_62, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongm>;


using _GemmHParamsT_63 = decltype(make_gemm_hparams(make_gemm_v2_hparams(cute::make_tuple(cute::Int<64>{},cute::Int<64>{},cute::Int<32>{}),cute::make_tuple(cute::Int<16>{},cute::Int<8>{},cute::Int<16>{}),_StreamkDP{}),None{},cute::make_tuple(cute::Int<256>{},cute::Int<128>{},cute::Int<32>{}),_GemmStreamK{},cute::Int<4>{},_RasterAlongN{}));
struct _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongn : public _GemmHParamsT_63 {
  using _GemmHParamsT_63::_GemmHParamsT_63;
};
using GemmHParamsT_63 = _64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongn;
using KernelBuilder_63 = GemmV2AGKernel_Kernel<GemmMetaT, GemmHParamsT_63>;
using GemmKernel_63 = decltype(KernelBuilder_63().gemm_kernel());
struct flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongn: public GemmKernel_63 {};
using GemmDevice_63 = GemmV2AGKernel_Device<GemmMetaT, GemmHParamsT_63, flux_bf16_bf16_bf16_bf16_fp32_fp32_sm80_a100_agkernel_rrr_gemmv2_false_nil_64x64x32_16x8x16_streamkdp_nil_256x128x32_gemmstreamk_4_rasteralongn>;

static bool _dummy_reg [[maybe_unused]] = (
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_0>(); }, GemmMetaT{},GemmHParamsT_0{},0),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_1>(); }, GemmMetaT{},GemmHParamsT_1{},1),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_2>(); }, GemmMetaT{},GemmHParamsT_2{},2),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_3>(); }, GemmMetaT{},GemmHParamsT_3{},3),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_4>(); }, GemmMetaT{},GemmHParamsT_4{},4),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_5>(); }, GemmMetaT{},GemmHParamsT_5{},5),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_6>(); }, GemmMetaT{},GemmHParamsT_6{},6),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_7>(); }, GemmMetaT{},GemmHParamsT_7{},7),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_8>(); }, GemmMetaT{},GemmHParamsT_8{},8),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_9>(); }, GemmMetaT{},GemmHParamsT_9{},9),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_10>(); }, GemmMetaT{},GemmHParamsT_10{},10),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_11>(); }, GemmMetaT{},GemmHParamsT_11{},11),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_12>(); }, GemmMetaT{},GemmHParamsT_12{},12),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_13>(); }, GemmMetaT{},GemmHParamsT_13{},13),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_14>(); }, GemmMetaT{},GemmHParamsT_14{},14),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_15>(); }, GemmMetaT{},GemmHParamsT_15{},15),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_16>(); }, GemmMetaT{},GemmHParamsT_16{},16),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_17>(); }, GemmMetaT{},GemmHParamsT_17{},17),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_18>(); }, GemmMetaT{},GemmHParamsT_18{},18),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_19>(); }, GemmMetaT{},GemmHParamsT_19{},19),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_20>(); }, GemmMetaT{},GemmHParamsT_20{},20),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_21>(); }, GemmMetaT{},GemmHParamsT_21{},21),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_22>(); }, GemmMetaT{},GemmHParamsT_22{},22),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_23>(); }, GemmMetaT{},GemmHParamsT_23{},23),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_24>(); }, GemmMetaT{},GemmHParamsT_24{},24),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_25>(); }, GemmMetaT{},GemmHParamsT_25{},25),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_26>(); }, GemmMetaT{},GemmHParamsT_26{},26),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_27>(); }, GemmMetaT{},GemmHParamsT_27{},27),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_28>(); }, GemmMetaT{},GemmHParamsT_28{},28),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_29>(); }, GemmMetaT{},GemmHParamsT_29{},29),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_30>(); }, GemmMetaT{},GemmHParamsT_30{},30),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_31>(); }, GemmMetaT{},GemmHParamsT_31{},31),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_32>(); }, GemmMetaT{},GemmHParamsT_32{},32),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_33>(); }, GemmMetaT{},GemmHParamsT_33{},33),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_34>(); }, GemmMetaT{},GemmHParamsT_34{},34),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_35>(); }, GemmMetaT{},GemmHParamsT_35{},35),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_36>(); }, GemmMetaT{},GemmHParamsT_36{},36),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_37>(); }, GemmMetaT{},GemmHParamsT_37{},37),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_38>(); }, GemmMetaT{},GemmHParamsT_38{},38),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_39>(); }, GemmMetaT{},GemmHParamsT_39{},39),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_40>(); }, GemmMetaT{},GemmHParamsT_40{},40),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_41>(); }, GemmMetaT{},GemmHParamsT_41{},41),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_42>(); }, GemmMetaT{},GemmHParamsT_42{},42),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_43>(); }, GemmMetaT{},GemmHParamsT_43{},43),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_44>(); }, GemmMetaT{},GemmHParamsT_44{},44),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_45>(); }, GemmMetaT{},GemmHParamsT_45{},45),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_46>(); }, GemmMetaT{},GemmHParamsT_46{},46),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_47>(); }, GemmMetaT{},GemmHParamsT_47{},47),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_48>(); }, GemmMetaT{},GemmHParamsT_48{},48),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_49>(); }, GemmMetaT{},GemmHParamsT_49{},49),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_50>(); }, GemmMetaT{},GemmHParamsT_50{},50),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_51>(); }, GemmMetaT{},GemmHParamsT_51{},51),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_52>(); }, GemmMetaT{},GemmHParamsT_52{},52),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_53>(); }, GemmMetaT{},GemmHParamsT_53{},53),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_54>(); }, GemmMetaT{},GemmHParamsT_54{},54),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_55>(); }, GemmMetaT{},GemmHParamsT_55{},55),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_56>(); }, GemmMetaT{},GemmHParamsT_56{},56),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_57>(); }, GemmMetaT{},GemmHParamsT_57{},57),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_58>(); }, GemmMetaT{},GemmHParamsT_58{},58),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_59>(); }, GemmMetaT{},GemmHParamsT_59{},59),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_60>(); }, GemmMetaT{},GemmHParamsT_60{},60),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_61>(); }, GemmMetaT{},GemmHParamsT_61{},61),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_62>(); }, GemmMetaT{},GemmHParamsT_62{},62),
  OpRegistry::instance().register_creator([]() { return std::make_unique<GemmDevice_63>(); }, GemmMetaT{},GemmHParamsT_63{},63),
true);